yawainu/config/routes.rb
Rails.application.routes.draw do

  # resources
  resources :user_sessions

  resources :users do
    resources :top
    resources :admin

    resources :categories do
      resources :galleries
    end
    resources :works
  end

  resources :covers
  resources :displays

  # rooting
  root 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

yawainu/app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id         :integer          not null, primary key
#  start_date :date             not null
#  end_date   :date             not null
#  comment    :text(65535)      not null
#  flag       :boolean          not null
#

class Work < ActiveRecord::Base
  belongs_to :user
end

yawainu/app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :require_login

  def index
    @h1_title = "仕事履歴"
    @user = User.find(params[:user_id])
    @work_new = "/users/#{params[:user_id]}/works/new"

    @back_link = "/users/#{params[:user_id]}/admin"
  end

  def new
    @h1_title = "仕事履歴追加"
    @user = User.find(params[:user_id])
    @work = @user.works.build

    @back_link = "/users/#{params[:user_id]}/works/"
  end

  def edit
    @h1_title = '仕事履歴編集'
    @user = User.find(params[:user_id])
    @work = @user.works.find(params[:id])

    @back_link = "/users/#{params[:user_id]}/works"
  end

  def create
    @user = User.find(params[:user_id])

    if @work = @user.works.create(work_params)
      redirect_to action: :index, notice: '更新しました'
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:user_id])
    @work = @user.works.find(params[:id])

    if @work.update(work_params)
      redirect_to action: :index, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @work = @user.works.find(params[:id])
    @work.destroy
    redirect_to user_works_path(params[:user_id])
  end

  private
    def work_params
      params.require(:work).permit(:start_date, :end_date, :comment, :flag)
    end
end

yawainu/app/views/works/_form.html.erb
<%= f.date_field :start_date %>
<%= f.date_field :end_date %>
<%= f.text_field :comment %>
<%= f.select :flag, [["表示", 1], ["非表示", 0]] %>

yawainu/app/views/works/_form_wrap.html.erb
<%= bootstrap_form_for([@user, @work]) do |f| %>
  <%= render 'shared/panel_body', f: f, form: 'works/form' %>
  <%= render 'shared/panel_footer', f: f, back_link: @back_link %>
<% end %>

yawainu/app/views/works/_list.html.erb
<table class="table table-striped">
  <tr>
    <th>start</th>
    <th>end</th>
    <th>comment</th>
    <th>app</th>
    <th></th>
  </tr>

  <%= render @user.works %>

</table>

yawainu/app/views/works/_work.html.erb
<tr>
  <td><%= work.start_date %></td>
  <td><%= work.end_date %></td>
  <td><%= work.comment %></td>
  <td><% if work.flag %>表示<% else %>非表示<% end %></td>
  <td>
    <%= link_to "編集", edit_user_work_path(:user_id => work.user, :id => work), {:class => "btn btn-success"} %>
    <%= link_to '削除', [work.user, work], method: :delete, :class => "btn btn-danger", data: {confirm: "削除しますか？"} %>
  </td>
</tr>

yawainu/app/views/works/index.html.erb
<%= render 'shared/panel_index', list: 'works/list', new_path: @work_new %>