yawainu/config/routes.rb
Rails.application.routes.draw do

  # resources
  resources :user_sessions

  resources :users do
    resources :top
    resources :admin

    resources :categories do
      resources :galleries
    end
    resources :works
  end

  resources :covers
  resources :displays

  # rooting
  root 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

yawainu/app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string(256)      not null
#  flag       :boolean          not null
#

class Category < ActiveRecord::Base
  belongs_to :user
  has_many :galleries, dependent: :destroy
end

yawainu/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login

  def index
    @h1_title = 'ギャラリー'
    @user = User.find(params[:user_id])
    @category_new = "/users/#{params[:user_id]}/categories/new"

    @back_link = "/users/#{params[:user_id]}/admin"
  end

  def new
    @h1_title = "カテゴリ追加"
    @user = User.find(params[:user_id])
    @category = @user.categories.build

    @back_link = "/users/#{params[:user_id]}/categories/"
  end

  def edit
    @h1_title = 'カテゴリ編集'
    @user = User.find(params[:user_id])
    @category = @user.categories.find(params[:id])

    @back_link = "/users/#{params[:user_id]}/categories/"
  end

  def create
    @user = User.find(params[:user_id])

    if @category = @user.categories.create(category_params)
      redirect_to action: :index, notice: '更新しました'
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:user_id])
    @category = @user.categories.find(params[:id])

    if @category.update(category_params)
      redirect_to action: :index, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @category = @user.categories.find(params[:id])
    @category.destroy
    redirect_to action: :index
  end


  private
    def category_params
      params.require(:category).permit(:title, :flag)
    end
end

yawainu/app/views/categories/_category.html.erb
<tr>
  <td><%= category.title %></td>
  <td><% if category.flag %>表示<% else %>非表示<% end %></td>
  <td>
    <%= link_to "登録", user_category_galleries_path(:user_id => category.user, :category_id => category), {:class => "btn btn-info"} %>
    <%= link_to "編集", edit_user_category_path(:user_id => category.user, :id => category), {:class => "btn btn-success"} %>
    <%= link_to '削除', [category.user, category], method: :delete, :class => "btn btn-danger", data: {confirm: "削除しますか？"} %>
  </td>
</tr>

yawainu/app/views/categories/_form.html.erb
<%= f.text_field :title %>
<%= f.select :flag, [["表示", 1], ["非表示", 0]] %>

yawainu/app/views/categories/_form_wrap.html.erb
<%= bootstrap_form_for([@user, @category]) do |f| %>
  <%= render 'shared/panel_body', f: f, form: 'categories/form' %>
  <%= render 'shared/panel_footer', f: f, back_link: @back_link %>
<% end %>

yawainu/app/views/categories/_list.html.erb
<h2>カテゴリ</h2>
<table class="table table-striped">
  <tr>
    <th>category</th>
    <th>entry</th>
    <th></th>
  </tr>

  <%= render @user.categories %>

</table>

yawainu/app/views/categories/edit.html.erb
<%= render 'form_wrap' %>

yawainu/app/views/categories/index.html.erb
<%= render 'shared/panel_index', list: 'categories/list', new_path: @category_new %>

yawainu/app/views/categories/new.html.erb
<%= render 'form_wrap' %>