yawainu/config/routes.rb
Rails.application.routes.draw do

  # resources
  resources :user_sessions

  resources :users do
    resources :top
    resources :admin

    resources :categories do
      resources :galleries
    end
    resources :works
  end

  resources :covers
  resources :displays

  # rooting
  root 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

yawainu/app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id         :integer          not null, primary key
#  image      :string(256)      not null
#  title      :string(256)      not null
#  comment    :text(65535)      not null
#  flag       :boolean          not null
#

class Gallery < ActiveRecord::Base
  belongs_to :category
end

yawainu/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :require_login

  def index
    @h1_title = 'ギャラリー'
    @user = User.find(params[:user_id])
    @category = @user.categories.find(params[:category_id])

    @gallery_new = "/users/#{params[:user_id]}/categories/#{params[:category_id]}/galleries/new"
    @back_link = "/users/#{params[:user_id]}/categories"
  end

  def new
    @h1_title = "ギャラリー追加"
    @user = User.find(params[:user_id])
    @category = @user.categories.find(params[:category_id])
    @gallery = @category.galleries.build

    @back_link = "/users/#{params[:user_id]}/categories/#{params[:category_id]}/galleries"
  end

  def edit
    @h1_title = 'ギャラリー編集'
    @user = User.find(params[:user_id])
    @category = @user.categories.find(params[:category_id])
    @gallery = @category.galleries.find(params[:id])

    @back_link = "/users/#{params[:user_id]}/categories/#{params[:category_id]}/galleries"
  end

  def create
    @user = User.find(params[:user_id])
    @category = @user.categories.find(params[:category_id])

    if @gallery = @category.galleries.create(gallery_params)
      redirect_to action: :index, notice: '更新しました'
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:user_id])
    @category = @user.categories.find(params[:category_id])
    @gallery = @category.galleries.find(params[:id])

    if @gallery.update(gallery_params)
      redirect_to action: :index, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @category = @user.categories.find(params[:category_id])
    @gallery = @category.galleries.find(params[:id])
    @gallery.destroy
    redirect_to action: :index
  end

  private
    def gallery_params
      params.require(:gallery).permit(:image, :title, :comment, :flag)
    end
end

yawainu/app/views/galleries/_form.html.erb
<%= f.file_field :image %>
<%= f.text_field :title %>
<%= f.text_field :comment %>
<%= f.select :flag, [["表示", 1], ["非表示", 0]] %>

yawainu/app/views/galleries/_form_wrap.html.erb
<%= bootstrap_form_for([@user, @category, @gallery]) do |f| %>
  <%= render 'shared/panel_body', f: f, form: 'galleries/form' %>
  <%= render 'shared/panel_footer', f: f, back_link: @back_link %>
<% end %>

yawainu/app/views/galleries/_gallery.html.erb
<tr>
  <td><%= gallery.title %></td>
  <td><% if gallery.flag %>表示<% else %>非表示<% end %></td>
  <td><%= gallery.comment %></td>
  <td>
    <%= link_to "編集", edit_user_category_gallery_path(:user_id => user, :category_id => gallery.category, :id => gallery), {:class => "btn btn-success"} %>
    <%= link_to '削除', [user, gallery.category, gallery], method: :delete, :class => "btn btn-danger", data: {confirm: "削除しますか？"} %>
  </td>
</tr>

yawainu/app/views/galleries/_list.html.erb
<h2>カテゴリ</h2>
<table class="table table-striped">
  <tr>
    <th>image</th>
    <th>title</th>
    <th>comment</th>
    <th>app</th>
    <th></th>
  </tr>

  <%= render @category.galleries, user: @user %>

</table>

yawainu/app/views/galleries/edit.html.erb
<%= render 'form_wrap' %>

yawainu/app/views/galleries/index.html.erb
<%= render 'shared/panel_index', list: 'galleries/list', new_path: @gallery_new %>

yawainu/app/views/galleries/new.html.erb
<%= render 'form_wrap' %>